# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45872c27e19ad91d1403e05a7e44e39c5053e783b5497ea5362c41bf59ce6f06fed822278356d45e038f8270b5a7d472748eaa97b5807c61b857ce25ef1e5e65

staging:
  secret_key_base: af5fc41ce63fc62746b188aa3d3a68a003a45b5b84bfb733a8a56d696056178eda49bbb4c1e963965cf226a5f1c6e18bc45b509b6be1621f97096e0c93d68b30

test:
  secret_key_base: 40ee8d13c01d9e60274bd4f4d16f463ba93377d9a75bfac0d106404953c67a748a3f5c7b84487c5ac30682c70eb3f1b5386d3caeb52c764f4655253905d7f41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
